# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be6e4dfaba3055eb3db7c0fc582852a56bf58198718867aee0ebab5cde0986fe7f736dc26254ba4d50b8fe91b38de5ad3290178ffcb2da26ef81794bdf5d8be6

test:
  secret_key_base: cb0a83760cfcd9a22fa3372800c3271b022cb786ff4667844c03b38406d429103e0c877abfa34e144ec67ed181f1c7d0775839d1eacb1674cd5dddee02a4b177

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
